common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from studyroom.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studyroom/', include('studyroom.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

studyroom/urls.py
from django.urls import path

from .views import base_views, student_views, account_views, bill_views, sugang_views, pay_views, absence_views, sms_views

app_name = 'studyroom'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:student_id>/',
         base_views.detail, name='detail'),
    path('priceplan/',
         base_views.priceplan, name='priceplan'),
    path('priceplan/create/',
         base_views.priceplan_create, name='priceplan_create'),
    path('hometax/',
         base_views.hometax, name='hometax'),

    # student_views.py
    path('student/create/',
         student_views.student_create, name='student_create'),
    path('student/modify/<int:student_id>/',
         student_views.student_modify, name='student_modify'),
    path('student/delete/<int:student_id>/',
         student_views.student_delete, name='student_delete'),

    # sugang_views.py
    path('sugang/',
         sugang_views.sugang_list, name='sugang_list'),
    path('sugang/create/<int:student_id>/',
         sugang_views.sugang_create, name='sugang_create'),
    path('sugang/modify/<int:student_id>/',
         sugang_views.sugang_modify, name='sugang_modify'),


    # account_views.py
    path('account/',
         account_views.account_list, name='account_list'),
    path('account/create/<int:student_id>/',
         account_views.account_create, name='account_create'),
    path('account/modify/<int:account_id>/',
         account_views.account_modify, name='account_modify'),
    path('account/delete/<int:account_id>/',
         account_views.account_delete, name='account_delete'),

    # absence_views.py
    path('absence/create/<int:student_id>/',
         absence_views.absence_create, name='absence_create'),
    path('absence/delete/<int:absence_id>/',
         absence_views.absence_delete, name='absence_delete'),

    # bill_views.py
    path('bill/',
         bill_views.bill_list, name='bill_list'),
    path('bill/bill_pay/',
         bill_views.bill_pay_list, name='bill_pay_list'),
    path('bill/bill_pay_con/',
         bill_views.bill_pay_con, name='bill_pay_con'),
    path('bill/bill_save/',
         bill_views.bill_save, name='bill_save'),

    # pay_views.py
    path('pay/',
         pay_views.pay_list, name='pay_list'),

    # sms_views.py
    path('sms/',
         sms_views.sms_list, name='sms_list'),
    path('sms/send/',
         sms_views.sms_send, name='sms_send'),
    path('sms/sendsms/',
         sms_views.send_sms, name='send_sms'),
]

studyroom/models.py
from django.db import models
from django.contrib.auth.models import User


class Student(models.Model):
    Grade_choices = (
        ('Y6','6세'),
        ('Y7','7세'),
        ('E1','1학년'),
        ('E2','2학년'),
        ('E3','3학년'),
        ('E4','4학년'),
        ('E5','5학년'),
        ('E6','6학년'),
    )

    def __str__(self):
        if self.brother:
            template = '{0.name} {0.grade} {0.brother.name}'
            return template.format(self)
        template = '{0.name} {0.grade}'
        return template.format(self)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    brother = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=20)
    grade = models.CharField(max_length=2, choices=Grade_choices)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    delete_yn = models.CharField(max_length=1, default='n')


class Account(models.Model):
    def __str__(self):
        if self.student.brother:
            return (self.student.name, self.student.brother.name)
        return (self.student.name)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True)
    payer = models.CharField(max_length=40, null=True, blank=True)
    payer_phone_num = models.CharField(max_length=11, null=True, blank=True)
    sms_phone_num = models.CharField(max_length=11, null=True, blank=True)
    recommend_dc_start = models.CharField(max_length=6, null=True, blank=True, default='yyyymm')
    recommend_dc_end = models.CharField(max_length=6, null=True, blank=True, default='yyyymm')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)


class PricePlan(models.Model):
    Grade_choices = (
        ('Y6', '6세'),
        ('Y7', '7세'),
        ('E1', '1학년'),
        ('E2', '2학년'),
        ('E3', '3학년'),
        ('E4', '4학년'),
        ('E5', '5학년'),
        ('E6', '6학년'),
    )

    class SugangType(models.TextChoices):
        Day3 = 'D3'
        Day4 = 'D4'

    def __str__(self):
        return (self.grade, self.sugang_type, self.start_mt, self.end_mt)

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    grade = models.CharField(max_length=2, choices=Grade_choices)
    sugang_type = models.CharField(max_length=2, choices=SugangType.choices)
    price = models.IntegerField()
    refund = models.IntegerField()
    start_mt = models.CharField(max_length=6, default='yyyymm')
    end_mt = models.CharField(max_length=6, default='999912')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)


class Sugang(models.Model):
    ClassId_choices = (
        ('MK','심미경'),
        ('AK','심애경'),
    )

    class Weekday(models.TextChoices):
        월요일 = 'MON'
        화요일 = 'TUE'
        수요일 = 'WED'
        목요일 = 'THU'
        금요일 = 'FRI'

    Time_choices = (
        ('1', '1시'),
        ('2', '2시'),
        ('3', '3시'),
        ('4', '4시'),
        ('5', '5시'),
    )

    def __str__(self):
        return (self.student.name, self.class_id, self.weekday, self.time, self.start_mt, self.end_mt)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True)
    class_id = models.CharField(max_length=2, choices=ClassId_choices)
    weekday = models.CharField(max_length=3, choices=Weekday.choices)
    time = models.CharField(max_length=1, choices=Time_choices)
    start_mt = models.CharField(max_length=6, default='yyyymm')
    end_mt = models.CharField(max_length=6, default='999912')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)


class Bill(models.Model):
    BillStatus_choices = (
        ('OP', '발행'),
        ('FP', '완납'),
        ('PP', '부분납'),
    )

    class PayType(models.TextChoices):
        김포페이 = 'KP'
        계좌이체 = 'AT'

    '''    
    def __str__(self):
        return (self.account.student.name, self.bill_mt)
    '''

    account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    bill_status = models.CharField(max_length=2, choices=BillStatus_choices)
    bill_mt = models.CharField(max_length=6)
    bill_amt = models.IntegerField(null=True, blank=True)
    base_amt = models.IntegerField(null=True, blank=True)
    brother_base_amt = models.IntegerField(null=True, blank=True, default=0)
    refund_amt = models.IntegerField(null=True, blank=True, default=0)
    brother_refund_amt = models.IntegerField(null=True, blank=True, default=0)
    brother_dc_amt = models.IntegerField(null=True, blank=True, default=0)
    recommend_dc_amt = models.IntegerField(null=True, blank=True, default=0)
    pay_amt = models.IntegerField(null=True, blank=True, default=0)
    pay_type = models.CharField(max_length=2, choices=PayType.choices, null=True, blank=True)
    pay_dt = models.CharField(max_length=8, null=True, blank=True)
    pay_id = models.IntegerField(null=True, blank=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(auto_now=True)


class Pay(models.Model):
    class PayType(models.TextChoices):
        김포페이 = 'KP'
        계좌이체 = 'AT'

    class PayStatus(models.TextChoices):
        미연결 = 'OP'
        연결 = 'CO'

    def __str__(self):
        return (self.pay_date)

    pay_type = models.CharField(max_length=2, choices=PayType.choices)
    pay_date = models.CharField(max_length=14, default='yyyymmddhhmmss')
    pay_amt = models.IntegerField()
    payer = models.CharField(max_length=30, null=True, blank=True)
    pay_status = models.CharField(max_length=2, choices=PayStatus.choices)
    account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, blank=True)
    bill = models.ForeignKey(Bill, on_delete=models.SET_NULL, null=True, blank=True)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(auto_now=True)


class Absence(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    student = models.ForeignKey(Student, on_delete=models.SET_NULL, null=True)
    absence_mt = models.CharField(max_length=6, default='yyyymm')
    absence_days = models.IntegerField(default=0)
    absence_detail = models.CharField(max_length=60,default='결석사유:')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(auto_now=True)

class Sms(models.Model):
    statusCode_choices = (
        ('200', 'OK'),
        ('202', 'Accept'),
        ('400', 'Bad Request'),
        ('401', 'Unauthorized'),
        ('403', 'Forbidden'),
        ('404', 'Not Found'),
        ('429', 'Too Many Requests'),
        ('500', 'Internal Server Error'),
    )
    account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    smstype = models.CharField(max_length=3)
    to = models.CharField(max_length=11)
    subject = models.CharField(max_length=50, null=True, blank=True)
    content = models.TextField(max_length=2000)
    requestId = models.CharField(max_length=32, null=True, blank=True)
    requestTime = models.CharField(max_length=50, null=True, blank=True)
    statusCode = models.CharField(max_length=3, null=True, blank=True, choices=statusCode_choices)
    statusName = models.CharField(max_length=10, null=True, blank=True)
    messageId = models.CharField(max_length=23, null=True, blank=True)
    messageStatus = models.CharField(max_length=15, null=True, blank=True)
    create_date = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

studyroom/views/absence_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AbsenceForm
from ..models import Student, Absence

import logging
logger = logging.getLogger('studyroom')

@login_required(login_url='common:login')
def absence_create(request, student_id):
    """
    결석 등록
    """
    student = get_object_or_404(Student, pk=student_id)
    if request.method == "POST":
        form = AbsenceForm(request.POST)
        if form.is_valid():
            absence = form.save(commit=False)
            absence.user = request.user
            absence.create_date = timezone.now()
            absence.student = student
            absence.save()
            return redirect('studyroom:detail', student_id=student.id)
    else:
        form = AbsenceForm()
    context = {'student': student, 'form': form, 'student_name':student.name}
    return render(request, 'studyroom/absence_form.html', context)

@login_required(login_url='common:login')
def absence_delete(request, absence_id):
    """
    결석 삭제
    """
    absence = get_object_or_404(Absence, pk=absence_id)
    student_id = absence.student.id
    absence.delete()
    return redirect('studyroom:detail', student_id=student_id)

studyroom/views/account_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.db.models import Q

from ..forms import  AccountForm
from ..models import Student, Account

import logging
logger = logging.getLogger('studyroom')

@login_required(login_url='common:login')
def account_create(request, student_id):
    """
    계정 등록
    """
    student = get_object_or_404(Student, pk=student_id)
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.user = request.user
            account.create_date = timezone.now()
            account.student = student
            account.save()
            return redirect('studyroom:detail', student_id=student.id)
    else:
        form = AccountForm()
    context = {'student': student, 'form': form}
    return render(request, 'studyroom/student_detail.html', context)

def account_list(request):
    logger.info("INFO 레벨로 출력")
    """
    계정 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    name = request.GET.get('name', '')  # 검색어

    # 조회
    account_list = Account.objects.order_by('id')
    if name:
        account_list = account_list.filter(
            Q(student__name__icontains=name) |  # 학생이름 검색
            Q(student__brother__name__icontains=name)  # 학생이름 검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(account_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'account_list': page_obj, 'page': page, 'name': name}
    return render(request, 'studyroom/account_list.html', context)

@login_required(login_url='common:login')
def account_modify(request, account_id):
    """
    pybo 질문수정
    """
    account = get_object_or_404(Account, pk=account_id)

    if request.method == "POST":
        form = AccountForm(request.POST, instance=account)
        if form.is_valid():
            account = form.save(commit=False)
            account.modify_date = timezone.now()  # 수정일시 저장
            account.save()
            return redirect('studyroom:detail', student_id=account.student.id)
    else:
        form = AccountForm(instance=account)
    context = {'form': form}
    return render(request, 'studyroom/account_form.html', context)


@login_required(login_url='common:login')
def account_delete(request, account_id):
    """
    pybo 질문삭제
    """
    account = get_object_or_404(Account, pk=account_id)
    student_id = account.student.id
    account.delete()
    return redirect('studyroom:detail', student_id=student_id)

studyroom/views/pay_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Q

from ..models import Pay
import logging
logger = logging.getLogger('studyroom')

@login_required(login_url='common:login')
def pay_list(request):
    logger.info("INFO 레벨로 출력")
    """
    수납 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    name = request.GET.get('name', '')  # 검색어

    # 조회
    pay_list = Pay.objects.order_by('-id')
    if name:
        pay_list = pay_list.filter(
            Q(account__student__name__icontains=name)   # 학생이름검색
        ).distinct()
    # 페이징처리
    paginator = Paginator(pay_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'pay_list': page_obj, 'page': page, 'name': name}
    return render(request, 'studyroom/pay_list.html', context)

studyroom/views/student_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import StudentForm
from ..models import Student


@login_required(login_url='common:login')
def student_create(request):
    """
    학생 등록
    """
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)
            student.user = request.user
            student.create_date = timezone.now()
            student.save()
            return redirect('studyroom:index')
    else:
        form = StudentForm()
    context = {'form': form}
    return render(request, 'studyroom/student_form.html', context)


@login_required(login_url='common:login')
def student_modify(request, student_id):
    """
    pybo 질문수정
    """
    student = get_object_or_404(Student, pk=student_id)

    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            student = form.save(commit=False)
            student.modify_date = timezone.now()  # 수정일시 저장
            student.save()
            return redirect('studyroom:detail', student_id=student.id)
    else:
        form = StudentForm(instance=student)
    context = {'form': form}
    return render(request, 'studyroom/student_form.html', context)


@login_required(login_url='common:login')
def student_delete(request, student_id):
    """
    pybo 질문삭제
    """
    student = get_object_or_404(Student, pk=student_id)
    student.delete()
    return redirect('studyroom:index')

templates/studyroom/account_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <div>
        <h1>
            <span class="badge badge-info">계정 등록/변경</span>
        </h1>
    </div>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <table class="table table-hover">
        {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/studyroom/sms_send.html
{% extends 'base.html' %}
{% load studyroom_filter %}
{% load humanize %}
{% block content %}

<div class="container my-3">
    <div>
        <h1>
            <span class="badge badge-info">SMS 발송 요청</span>
        </h1>
    </div>


    <hr class="my-3">
    <form method="post" class="post-form my-3" action="{% url 'studyroom:send_sms' %}">
    <div class="row">
        {% csrf_token %}

        <div  style="overflow:scroll; width:350px; height:650px;">
        <table class="table">
            <thead>
            <tr class="text-center thead-light">
                <th>전체<input type="checkbox" id="allchk"></th>
                <th>이름</th>
                <th>폰번호</th>
            </tr>
            </thead>
            <tbody>
            {% if account_list %}
            {% for account in account_list %}
            <tr class="text-center">
                <td>
                    <input type="checkbox" name="account_id" value={{ account.id }}>
                </td>
                <td>{{ account.student.name }}{{ account.student.brother.name }}</td>
                <td>{{ account.sms_phone_num|default_if_none:"미등록" }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">account이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        </div>
        <div class="col-xs-2">
                <button class="btn " type="button" >내용</button>
        </div>
        <div class="col-xs-2" >
            <textarea id="textBox" class="form-control" name="content" cols="30" rows="10" maxlength="200" ></textarea>
            <p class="textCount">0bytes</p>
        </div>

        <div class="col-xs-2">
            <button type="submit" class="btn btn-secondary">SMS 발송</button>
        </div>
    </div>
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$('#textBox').keyup(function (e) {
    let content = $(this).val();
 if (content.length == 0 || content == '') {
     $('.textCount').text('0bytes');
 }
 else { $('.textCount').text(content.length + 'bytes');
 }
});
$('#allchk').click(function(){
    var checked = $('#allchk').is(':checked');
    if(checked)
        $('input:checkbox').prop('checked',true);
    else
        $('input:checkbox').prop('checked',false);
});
</script>
{% endblock %}

templates/studyroom/student_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <div>
        <h1>
            <span class="badge badge-info">학생 정보</span>
        </h1>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center thead-light">
            <th>학생</th>
            <th>학년</th>
            <th>형제</th>
            <th>계정번호</th>
        </tr>
        </thead>
        <tbody>
        <tr class="text-center">
            <td>{{ student.name }}</td>
            <td>{{ student.get_grade_display }}</td>
            <td>{{ student.brother.name }}</td>
            <td>{{ student.account_set.all.first.id }} {{ student.brother.account_set.all.first.id }}</td>
        </tr>
        </tbody>
    </table>
    <div class="my-3">
        <a href="{% url 'studyroom:student_modify' student.id  %}"
           class="btn btn-secondary">수정</a>
        <a href="#" class="delete btn btn-secondary"
            data-uri="{% url 'studyroom:student_delete' student.id  %}">삭제</a>
    </div>

    <hr class="my-3">
    <div class="my-3">
        <h1>
            <span class="badge badge-info">계정 정보</span>
        </h1>
    </div>
    {% if  student.account_set.all.first.id %}
    <table class="table">
        <thead>
        <tr class="text-center thead-secondary">
            <th>계정번호</th>
            <th>학생</th>
            <th>형제</th>
            <th>납부자</th>
            <th>납부자 전화번호</th>
            <th>형제할인</th>
            <th>추천할인(from)</th>
            <th>추천할인(to)</th>
        </tr>
        </thead>
        <tbody>
        <tr class="text-center">
            <td>{{ student.account_set.all.first.id }}</td>
            <td>{{ student.account_set.all.first.student.name }}</td>
            <td>{{ student.account_set.all.first.student.brother.name|default_if_none:"미등록" }}</td>
            <td>{{ student.account_set.all.first.payer|default_if_none:"미등록" }}</td>
            <td>{{ student.account_set.all.first.payer_phone_num|default_if_none:"미등록" }}</td>
            <td>{{ student.account_set.all.first.brother_dc_yn }}</td>
            <td>{{ student.account_set.all.first.recommend_dc_start|default_if_none:"" }}</td>
            <td>{{ student.account_set.all.first.recommend_dc_end|default_if_none:"" }}</td>
        </tr>
        </tbody>
    </table>
    <div class="my-3">
        <a href="{% url 'studyroom:account_modify' student.account_set.all.first.id  %}"
           class="btn btn-secondary">수정</a>
        <a href="#" class="delete btn btn-secondary"
            data-uri="{% url 'studyroom:account_delete' student.account_set.all.first.id  %}">삭제</a>
    </div>
    {%  elif student.brother.account_set.all.first.id %}
    <table class="table">
        <thead>
        <tr class="text-center thead-secondary">
            <th>번호</th>
            <th>이름</th>
            <th>형제</th>
            <th>납부자</th>
            <th>납부자 전화번호</th>
            <th>형제할인</th>
            <th>추천할인(from)</th>
            <th>추천할인(to)</th>
        </tr>
        </thead>
        <tbody>
        <tr class="text-center">
            <td>{{ student.brother.account_set.all.first.id }}</td>
            <td>{{ student.brother.account_set.all.first.student.name }}</td>
            <td>{{ student.brother.account_set.all.first.student.brother.name }}</td>
            <td>{{ student.brother.account_set.all.first.payer|default_if_none:"미등록"  }}</td>
            <td>{{ student.brother.account_set.all.first.payer_phone_num|default_if_none:"미등록"  }}</td>
            <td>{{ student.brother.account_set.all.first.brother_dc_yn }}</td>
            <td>{{ student.brother.account_set.all.first.recommend_dc_start|default_if_none:""  }}</td>
            <td>{{ student.brother.account_set.all.first.recommend_dc_end|default_if_none:""  }}</td>
        </tr>
        </tbody>
    </table>
    <div class="my-3">
        <a href="{% url 'studyroom:account_modify' student.brother.account_set.all.first.id  %}"
           class="btn btn-secondary">수정</a>
        <a href="#" class="delete btn btn-secondary"
            data-uri="{% url 'studyroom:account_delete' student.brother.account_set.all.first.id  %}">삭제</a>
    </div>
    {% else %}
    <h5>등록된 계정이 없습니다.</h5>
    <form action="{% url 'studyroom:account_create' student.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        {{ form.as_p }}
        <input type="submit" value="계정 등록" class="btn btn-secondary">
    </form>
    {% endif %}

    <hr class="my-3">
    <div class="my-3">
        <h1>
            <span class="badge badge-info">수강 정보</span>
        </h1>
    </div>
    {% if sugang_list %}
    {% regroup sugang_list by class_id as class_list %}
    {% for class_id, time_list in class_list %}
    <h3><span class="badge badge-info">{{ class_id }}</span></h3>
    <table class="table">
        <thead>
        <tr class="text-center thead-secondary ">
            <th>시간</th>
            <th>월</th>
            <th>화</th>
            <th>수</th>
            <th>목</th>
        </tr>
        </thead>
        <tbody>
        {% regroup time_list by time as weekday_list %}
        {% for time, sugangs in weekday_list %}
        <tr class="text-center">
            <td>{{ time }}시</td>
            <td>
                {% for sugang in sugangs %}
                {% if sugang.weekday == 'MON' %}{{ sugang.start_mt }}{% endif %}
                {% endfor %}
            </td>
            <td>
                {% for sugang in sugangs %}
                {% if sugang.weekday == 'TUE' %}{{ sugang.start_mt }}{% endif %}
                {% endfor %}
            </td>
            <td>
                {% for sugang in sugangs %}
                {% if sugang.weekday == 'WED' %}{{ sugang.start_mt }}{% endif %}
                {% endfor %}
            </td>
            <td>
                {% for sugang in sugangs %}
                {% if sugang.weekday == 'THU' %}{{ sugang.start_mt }}{% endif %}
                {% endfor %}
            </td>
        {% endfor %}
        </tbody>
    </table>
    {% endfor %}
    <div class="my-3">
        <a href="{% url 'studyroom:sugang_modify' student.id  %}"
           class="btn btn-secondary">수정</a>
    </div>
    {% else %}
    <div>
        <h5>데이터가 없습니다.</h5>
    </div>
    <a href="{% url 'studyroom:sugang_create' student.id %}" class="btn btn-secondary">수강 등록</a>

    {% endif %}
    <hr class="my-3">
    <div class="my-3">
        <h1>
            <span class="badge badge-info">결석 정보</span>
        </h1>
    </div>
    {% if student.absence_set.all %}
    <div >
        {% for absence in student.absence_set.all %}
            <div>
                <h5>
                    {{ absence.absence_mt }}월 : 결석일수 {{ absence.absence_days }}일
                    <a href="#" class="absence_delete btn btn-secondary"
            data-uri="{% url 'studyroom:absence_delete' absence.id  %}">삭제</a>
                </h5>
            </div>
        {% endfor %}
    </div>
        <a href="{% url 'studyroom:absence_create' student.id %}" class="btn btn-secondary">결석 등록</a>

    {% else %}
    <div>
        <h5>데이터가 없습니다.</h5>
    </div>
    <a href="{% url 'studyroom:absence_create' student.id %}" class="btn btn-secondary">결석 등록</a>
    {% endif %}

</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".absence_delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}