common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from studyroom.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studyroom/', include('studyroom.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

studyroom/urls.py
from django.urls import path

from .views import base_views, student_views, account_views, bill_views, sugang_views, pay_views, absence_views, sms_views

app_name = 'studyroom'

urlpatterns = [
    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:student_id>/',
         base_views.detail, name='detail'),
    path('priceplan/',
         base_views.priceplan, name='priceplan'),
    path('priceplan/create/',
         base_views.priceplan_create, name='priceplan_create'),
    path('hometax/',
         base_views.hometax, name='hometax'),

    # student_views.py
    path('student/create/',
         student_views.student_create, name='student_create'),
    path('student/modify/<int:student_id>/',
         student_views.student_modify, name='student_modify'),
    path('student/delete/<int:student_id>/',
         student_views.student_delete, name='student_delete'),

    # sugang_views.py
    path('sugang/',
         sugang_views.sugang_list, name='sugang_list'),
    path('sugang/create/<int:student_id>/',
         sugang_views.sugang_create, name='sugang_create'),
    path('sugang/modify/<int:student_id>/',
         sugang_views.sugang_modify, name='sugang_modify'),


    # account_views.py
    path('account/',
         account_views.account_list, name='account_list'),
    path('account/create/<int:student_id>/',
         account_views.account_create, name='account_create'),
    path('account/modify/<int:account_id>/',
         account_views.account_modify, name='account_modify'),
    path('account/delete/<int:account_id>/',
         account_views.account_delete, name='account_delete'),

    # absence_views.py
    path('absence/create/<int:student_id>/',
         absence_views.absence_create, name='absence_create'),
    path('absence/delete/<int:absence_id>/',
         absence_views.absence_delete, name='absence_delete'),

    # bill_views.py
    path('bill/',
         bill_views.bill_list, name='bill_list'),
    path('bill/bill_pay/',
         bill_views.bill_pay_list, name='bill_pay_list'),
    path('bill/bill_pay_con/',
         bill_views.bill_pay_con, name='bill_pay_con'),
    path('bill/bill_save/',
         bill_views.bill_save, name='bill_save'),

    # pay_views.py
    path('pay/',
         pay_views.pay_list, name='pay_list'),

    # sms_views.py
    path('sms/',
         sms_views.sms_list, name='sms_list'),
    path('sms/send/',
         sms_views.sms_send, name='sms_send'),
    path('sms/sendsms/',
         sms_views.send_sms, name='send_sms'),
]

studyroom/views/base_views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django.shortcuts import render
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http.response import HttpResponse
from ..serializer import PostSerializer


from ..models import Student, Sugang, PricePlan, Account, Pay

@login_required(login_url='common:login')
def index(request):
    """
    학생 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    name = request.GET.get('name', '')  # 검색어

    # 조회
    student_list = Student.objects.order_by('-id')
    if name:
        student_list = student_list.filter(
            Q(name__icontains=name)
        ).distinct()


    # 페이징처리
    paginator = Paginator(student_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'student_list': page_obj, 'page': page, 'name': name}
    return render(request, 'studyroom/student_list.html', context)

@login_required(login_url='common:login')
def detail(request, student_id):
    """
    학생 상세정보(계정,수강) 출력
    """
    work_mt = datetime.today().strftime("%Y%m")
    student = get_object_or_404(Student, pk=student_id)
    sugang_list = Sugang.objects.order_by('class_id', 'time').filter(student=student, end_mt__gte = work_mt)

    context = {'student': student, 'sugang_list': sugang_list}
    return render(request, 'studyroom/student_detail.html', context)

@login_required(login_url='common:login')
def priceplan(request):
    """
    요금표 출력
    """
    pricepln_list = PricePlan.objects.order_by('grade', 'sugang_type')

    context = {'priceplan_list': pricepln_list}
    return render(request, 'studyroom/priceplan.html', context)

@login_required(login_url='common:login')
def priceplan_create(request):
    """
        요금표 생성
    """
    grade = request.POST.get('grade', '')  # 검색어
    sugang_type = request.POST.get('sugang_type', '')  # 검색어
    price = request.POST.get('price', '')  # 검색어
    refund = request.POST.get('refund', '')  # 검색어
    start_mt = request.POST.get('start_mt', '')  # 검색어

    print('==== create priceplan : ',grade, sugang_type, price, refund, start_mt)

    try:
        priceplan = PricePlan.objects.get(grade=grade, sugang_type=sugang_type, end_mt='999912')

        if priceplan.start_mt >= start_mt:
            print('==== error : start_mt alread exist')
        else:
            start_yy = start_mt[:4]
            start_mm = start_mt[-2:]
            end_mt = (date(int(start_yy), int(start_mm), 1) + relativedelta(months=-1)).strftime("%Y%m")
            priceplan.end_mt = end_mt
            priceplan.save()
    except:
        print('=== new price plan')
    finally:
        new_priceplan = PricePlan(grade=grade, sugang_type=sugang_type, price=price, refund=refund, start_mt=start_mt,
                                  end_mt='999912', create_date=timezone.now())
        new_priceplan.save()

    """
    요금표 출력
    """
    pricepln_list = PricePlan.objects.order_by('grade', 'sugang_type')

    context = {'priceplan_list': pricepln_list}
    return render(request, 'studyroom/priceplan.html', context)


@api_view(['POST'])
def hometax(request):
    print('=== hometax post api start ===')
    if request.method == 'GET':
        return HttpResponse(status=200)
    if request.method == 'POST':
        serializer = PostSerializer(data = request.data, required=False)
        serializer.create_date = timezone.now()
        try:
            serializer.account = Account.objects.get(payer_phone_num__contains=serializer.payer)
        except:
            print('=== account is None ')

        if(serializer.is_valid()):
            serializer.save()
            return Response(serializer.data ,status=200)
        return Response(serializer.errors ,status=status.HTTP_400_BAD_REQUEST)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>키즈아카데미 공부방</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'studyroom:index' %}">키즈아카데미 공부방</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:index' %}">학생</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:account_list' %}">계정</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:sugang_list' %}">수강표</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:priceplan' %}">요금표</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:bill_list' %}">청구</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:bill_save' %}">재발행</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:pay_list' %}">수납</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:sms_send' %}">SMS발송</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'studyroom:sms_list' %}">SMS이력</a>
            </li>
        </ul>
    </div>
</nav>